# Generated by Django 4.2 on 2023-04-29 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_team_members_team_accepted_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invites',
            field=models.ManyToManyField(blank=True, related_name='invites', to='base.team'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('repo', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pteam', to='base.team')),
            ],
        ),
    ]
