# Generated by Django 4.2 on 2023-04-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_invites_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='repo',
        ),
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
