# Generated by Django 4.2 on 2023-04-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_organization_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='image',
        ),
    ]
